version: 2.1

jobs:
  node-test:
    docker:
      - image: node:4.4.6
    resource_class: 'medium+'
    steps:
      - checkout
      - run: |
          node -v
          npm -v
      - run: |
          npm install

workflows:
  main:
    jobs:
      - node-test
