version: 2.1

jobs:
  node-test:
    docker:
      - image: node:14
    resource_class: 'small'
    steps:
      - run: |
          node -v
          npm -v
      - run: |
          sleep 30
          exit 1
          

workflows:
  main:
    jobs:
      - node-test
