version: 2.1

jobs:
  node-test:
    docker:
      - image: node:14
    resource_class: 'medium+'
    steps:
      - checkout
      - run: |
          node -v
          npm -v
      - run: |
          npm i -g gifsicle@0.1.7 jpegtran-bin@0.2.8 optipng-bin@0.3.11 pngquant-bin@0.1.7
          npm i
          

workflows:
  main:
    jobs:
      - node-test
