version: 2.1

commands:
  install_deps:
    description: Install Node dependencies
    steps:
      - restore_cache:
          keys:
            - foobar-{{ checksum "yarn.lock" }}
      - run: ls -la
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --network-concurrency 1

      - save_cache:
          key: foobar-{{ checksum "yarn.lock" }}
          paths:
            - node_modules



jobs:
  node-test:
    parameters:
      img:
        type: string
        default: cimg/node:16.13.1-browsers
    docker:
      - image: << parameters.img >>
    resource_class: 'medium+'
    working_directory: ~/core/web
    steps:
      - checkout:
          path: ~/core
      - run: |
          pwd
      - run: |
          node -v
      - install_deps
      - run: |
          node index.js

  generate_bindings:
    parameters:
      img:
        type: string
    working_directory: ~/apps
    machine:
      image: << parameters.img >>
    resource_class: medium
    steps:
    - checkout
    - run:
        name: Inspect Node
        command: |
          node -v
          npm -v
          which npx
    - run:
        name: Lerna
        command: npx lerna --help

workflows:
  main:
    jobs:
      - generate_bindings:
          matrix:
            parameters:
              img:
                - ubuntu-2004:202010-01
                - ubuntu-2004:202111-02
                - ubuntu-2004:202201-02
                - ubuntu-2004:2022.07.1
